use_frameworks!

target 'VersaPlayerTest_macOS' do
  platform :osx, '10.13'
  pod 'VersaPlayer', :path => '../'
end

target 'VersaPlayerTest_iOS' do
  platform :ios, '9.0'
  pod 'VersaPlayer', :path => '../'
end

target 'VersaPlayerTest_tvOS' do
  platform :tvos, '9.0'
  pod 'VersaPlayer', :path => '../'
end
